### ISSUE TITLE
secrets.json not found

### ISSUE THREAD

**Issue by darrenchang** [RealTimeWeb/Blockpy-Server#3]
The command ```python3 manage.py reset_db``` returns the below error.
```
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from main import app
  File "/Users/darren/Documents/gitlab/blockpy/blockpy/Blockpy-Server/main.py", line 11, in <module>
    with open('secrets.json') as secrets_file:
FileNotFoundError: [Errno 2] No such file or directory: 'secrets.json'
```

**Comment by acbart** [comment]
[https://github.com/acbart/Blockpy-Server](https://github.com/acbart/Blockpy-Server)

**Comment by darrenchang** [comment]
> https://github.com/acbart/Blockpy-Server

Thank you so much. I'll give it a try.
